name: UiPath CI/CD Pipeline

name: UiPath Automation Workflow

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install UiPath Studio
        uses: toniblyx/setup-uipath@v1

      - name: Build and Test Automation Project
        run: |
          # Add commands to build and test your UiPath automation project here

      - name: Deploy to Orchestrator
        run: |
          # Add commands to deploy your automation project to UiPath Orchestrator here
